### ISSUE TITLE
Créer la commande init 

### ISSUE THREAD

**Issue by alecberney** [gen-classroom/projet-berney_forestier_herzig#28]

**Comment by QuentinForestier** [comment]
C'est la commande qui permet l'initialisation du site statique avec les fichiers de base.

**Comment by MelvynHerzig** [comment]
2h.
Il m'a fallu plus de temps que prévu, je n'arrivais pas à faire fonctionner les chemins en argument de commande avec picocli.
De plus j'ai eu de la peine à créer les fichiers.

Je me suis documenté et ça a marché mais ça a pris plus de temps que prévu.
