### ISSUE TITLE
Créer une commande --version [au mieux 1h, au pire 2h, attendu 1h30]

### ISSUE THREAD

**Issue by alecberney** [gen-classroom/projet-berney_forestier_herzig#29]

**Comment by MelvynHerzig** [comment]
J'ai trouvé une solution sur StackOverflow
https://stackoverflow.com/questions/3697449/retrieve-version-from-maven-pom-xml-in-code/41791885
je vais tenter de l'implémenter

**Comment by MelvynHerzig** [comment]
Temps consacré 1h45
