### ISSUE TITLE
Interpréter un fichier Markdown

### ISSUE THREAD

**Issue by alecberney** [gen-classroom/projet-berney_forestier_herzig#30]

**Comment by QuentinForestier** [comment]
Le programme doit pouvoir lire un fichier Markdown et interprété sa structure.

**Comment by QuentinForestier** [comment]
Je prends en charge cette issue. J'estime le temps d'implémentation à 1 heure environ.

**Comment by MelvynHerzig** [comment]
J'adore ce que tu fais !
