### ISSUE TITLE
Implémenter le code permettant de créer la structure de base du site statique 

### ISSUE THREAD

**Issue by QuentinForestier** [gen-classroom/projet-berney_forestier_herzig#33]
L'arborescence de base doit pouvoir :

- [x] Créer ou enrichir le dossier passé en paramètre
- [x] Ajouter Le ficher config.yaml
- [x] Ajouter le fichier index.md

**Comment by MelvynHerzig** [comment]
Doublon de la commande init, je ferme cette issue
