### ISSUE TITLE
Rendre le projet téléchargeable depuis l'onglet Release de GitHub

### ISSUE THREAD

**Issue by QuentinForestier** [gen-classroom/projet-berney_forestier_herzig#36]
Créer le tag git (v0.0.1) correspondant à la release.
Des instructions d'installations doivent être fournies.

**Comment by MelvynHerzig** [comment]
Au mieux 30minutes, au pire 1h, attendu 45minutes

**Comment by MelvynHerzig** [comment]
Realease publiée, fin du sprint 1
