### ISSUE TITLE
Publication de release automatique avec GitHub Action

### ISSUE THREAD

**Issue by QuentinForestier** [gen-classroom/projet-berney_forestier_herzig#48]
En tant que développeur, j’aimerai que la création et la publication d’une nouvelle release soit automatisée à l’aide
de GitHub actions. En d’autres termes, j’aimerai que le fichier jar ou le fichier zip de la release soit publié de
manière automatique lorsqu’un tag correspondant à une version (p. ex. v0.0.2) est publié sur git.

**Comment by MelvynHerzig** [comment]
Temp prévu 1h, au mieux 45min, au pire 2h, temps réel = 2h

J'ai effectué sur un repo personnel différent test d'actions.
Je pensais arriver facilement à mes fins. Malheureusement, je n'arrivais pas à faire à upload le fichier target/statique.zip en tant qu'asset. J'ai testé divers actions 
 - https://github.com/marketplace/actions/automatic-releases
 - https://github.com/softprops/action-gh-release
 - https://github.com/actions/create-release

Je souhaitais vraiment faire en sorte que l'utilisateur puisse directement télécharger le bon asset. J'ai finalement réussi avec la dernière.

J'ai également perdu du temps car les GA ne se mettaient pas forcément à jour lorsque j'éditais le fichier yml correspondant. Je devais recréer un repository de test à chaque fois que je souhaitais tester une nouvelle méthode.

Petit bonus, on peut automatiquement y ajouter le readme en guise de description.

**Comment by alecberney** [comment]
ferme #48

**Comment by alecberney** [comment]
ferme #48
