### ISSUE TITLE
Modifier la commande init

### ISSUE THREAD

**Issue by QuentinForestier** [gen-classroom/projet-berney_forestier_herzig#50]
La commande init doit en plus créer un dossier template contenant :
- layout.html
- menu.html

Les 2 fichiers doivent aussi avoir leur contenu.

**Comment by alecberney** [comment]
Pair programming

**Comment by MelvynHerzig** [comment]
Temp prévu 2h, au mieux 1h, au pire 2h30, temps réel = 1h30

Tout s'est déroulé correctement, les test on pris un petit peu plus de temps que prévu. Erreur dans la gestion des chemins
