### ISSUE TITLE
Modifier la commande build

### ISSUE THREAD

**Issue by QuentinForestier** [gen-classroom/projet-berney_forestier_herzig#51]
La commande build doit être modifier de tel façon : 

- [x]  Les fichiers HTML doivent maintenant se baser sur le fichier template/layout.html en utilisant un moteur de template
- [x]  Il faut supprimer le dossier template copié dans le dossier build

**Comment by alecberney** [comment]
Pair programming

**Comment by alecberney** [comment]
Estimation du temps:
Au mieux 3h
Au pire 6h
attendu 4h30
en pair programming

**Comment by alecberney** [comment]
1h20 passées le 22.04.2021

**Comment by alecberney** [comment]
2h passées le 29.04.2021

**Comment by alecberney** [comment]
20min passées le 29.04.2021 (plus tard)

**Comment by QuentinForestier** [comment]
45 minutes passées le 06.05.2021

**Comment by QuentinForestier** [comment]
Temps total : 4h25
