### ISSUE TITLE
Corriger warnings dans la commande build

### ISSUE THREAD

**Issue by MelvynHerzig** [gen-classroom/projet-berney_forestier_herzig#57]
Lors de la compilation du projet sous maven avec clean install, des warnings indique que la commande build n'est pas sécurisée, tenter de comprendre d'où ça vient et tenter un correctif si applicable.

**Comment by QuentinForestier** [comment]
Estimation du temps:
Au mieux 30minutes
Au pire 2h
attendu 1h30

**Comment by QuentinForestier** [comment]
Temps effectif : 30 minutes
