### ISSUE TITLE
Intégrer l'option --watch à build et à serve

### ISSUE THREAD

**Issue by MelvynHerzig** [gen-classroom/projet-berney_forestier_herzig#58]
L'effet sur les deux commandes sera semblable.
Vérifier si des changements apparaissent dans le dossier du site ( cd .. par rapport au dossier de build)
Détecter ces changements 
Regénérer le fichier correspondant.
Question ouverte: Basiquement cette procédure interviendra sur les fichiers de md, que peut-on faire sur le fichier de template, le fichier de config ? Est-ce qu'on les ignore, et ce qu'on regénère tout le build ?

**Comment by QuentinForestier** [comment]
Estimation du temps:
Au mieux 4h
Au pire 10h
attendu 9h

**Comment by QuentinForestier** [comment]
Temps effectif : 8h
