### ISSUE TITLE
Configurer Jacoco pour calculer le degré de couverture des T.U et T.I.

### ISSUE THREAD

**Issue by MelvynHerzig** [gen-classroom/projet-berney_forestier_herzig#60]
Ajouter les données au rapport

**Comment by MelvynHerzig** [comment]
https://www.eclemma.org/jacoco/

**Comment by alecberney** [comment]
Estimation du temps:
Au mieux 1h
Au pire 3h
attendu 1h30

**Comment by alecberney** [comment]
passés 1h le 20.05.2021
Jacoco ajouté

**Comment by alecberney** [comment]
passés 45min le 03.06.2021
J'ai ajouté un petit tuto dans le readme qui explique comment un rapport de test avec du code coverage et comment le lire.

**Comment by alecberney** [comment]
Total final = 1h45 proche de l'estimation 1h30
